### ISSUE TITLE
Pinging for specific players logging in

### ISSUE THREAD

**Issue by ElBennyX** [Maxopoly/Kira#8]
Add something like `skynetpingformat` so that you can get pinged whenever a specific person appears on the skynet. Maybe even a way to chose between logins, logouts, or both

**Comment by Maxopoly** [comment]
Would it be acceptable if I simply made https://github.com/Maxopoly/Kira/wiki/Relays#everyoneformat apply to skynet as well?

**Comment by ElBennyX** [comment]
Yea, that could work too. Making it possible to turn off logouts would be nice though

**Comment by Maxopoly** [comment]
Fixed long ago afaik
